/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AmbulanceAssistant;

import Business.EcoSystem;
import Business.EnterPrise.Enterprise;
import Business.Network.Network;
import Business.Organization.AmbulanceAssistantOrganization;
import Business.Organization.AmbulanceReceptionistOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.PatientVisit.VitalSign;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VitalAlertRequestToAmbulanceReception;
import Business.WorkQueue.VitalAlertTestRequestToNurse;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samar
 */
public class AmbulanceAssistantWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AmbulanceAssistantWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    private AmbulanceAssistantOrganization ambulanceAssistantOrganization;

    public AmbulanceAssistantWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.ecoSystem = business;
        valueLabel.setText(organization.getOrgName());
        populateAlertRequestCombobox();
        populateAlertRequestTable("Sent to Amblance Assistant");
        populateCriticalAlertRequest();
        populateCriticalAlertRequestTable("Sent to Amblance Assistant");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alertRequestTable = new javax.swing.JTable();
        AcceptBtnSecond = new javax.swing.JButton();
        viewBtn1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        respRateTxt1 = new javax.swing.JTextField();
        heartRateTxt1 = new javax.swing.JTextField();
        sysBloodPresTxt1 = new javax.swing.JTextField();
        weightInPoundsTxt1 = new javax.swing.JTextField();
        alertRequestCombo = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        criticalAlertRequestTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        respRateTxt2 = new javax.swing.JTextField();
        heartRateTxt2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        viewBtn2 = new javax.swing.JButton();
        sysBloodPresTxt2 = new javax.swing.JTextField();
        weightInPoundsTxt2 = new javax.swing.JTextField();
        crtiticalAlertCombox = new javax.swing.JComboBox();
        AcceptBtn = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ambulance Assistant Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        alertRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Requested Date", "Message", "PatientMRN", "Status", "Nurse Receiver", "Received Date", "Ambulance Receptionist", "Ambulance Recep Request Date", "Ambulance Assistant", "Ambulance Assistant Date"
            }
        ));
        jScrollPane2.setViewportView(alertRequestTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 1270, 130));

        AcceptBtnSecond.setText("Accept");
        AcceptBtnSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBtnSecondActionPerformed(evt);
            }
        });
        add(AcceptBtnSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 110, 35));

        viewBtn1.setText("View");
        viewBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtn1ActionPerformed(evt);
            }
        });
        add(viewBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 790, 90, 35));

        jLabel6.setText("Respiratory Rate:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 690, 120, -1));

        jLabel7.setText("Heart Rate:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 730, 100, -1));

        jLabel8.setText("Systolic blood Pressure:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 690, 140, -1));

        jLabel9.setText("Weight in Pounds:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 740, 110, -1));

        respRateTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respRateTxt1ActionPerformed(evt);
            }
        });
        add(respRateTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 690, 120, -1));
        add(heartRateTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 730, 120, -1));
        add(sysBloodPresTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 690, 120, -1));
        add(weightInPoundsTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 740, 120, -1));

        alertRequestCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        alertRequestCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertRequestComboActionPerformed(evt);
            }
        });
        add(alertRequestCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, 160, 35));

        criticalAlertRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Requested Date", "Message", "PatientMRN", "Status", "Ambulance Receptionist", "Receiver Date", "Ambulance Assistant", "Ambulance Recep Request Date"
            }
        ));
        jScrollPane3.setViewportView(criticalAlertRequestTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, 1190, 90));

        jLabel10.setText("Respiratory Rate:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 273, 120, -1));

        jLabel11.setText("Heart Rate:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 313, 100, -1));

        jLabel12.setText("Systolic blood Pressure:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 273, 140, -1));

        jLabel13.setText("Weight in Pounds:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 323, 110, -1));

        respRateTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respRateTxt2ActionPerformed(evt);
            }
        });
        add(respRateTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 273, 120, -1));
        add(heartRateTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 313, 120, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Critical Alert Work Request from Patient, based on Vital Sign:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 103, -1, -1));

        viewBtn2.setText("View");
        viewBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtn2ActionPerformed(evt);
            }
        });
        add(viewBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 90, 35));
        add(sysBloodPresTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 273, 120, -1));
        add(weightInPoundsTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 323, 120, -1));

        crtiticalAlertCombox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        crtiticalAlertCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crtiticalAlertComboxActionPerformed(evt);
            }
        });
        add(crtiticalAlertCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 230, 35));

        AcceptBtn.setText("Accept");
        AcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBtnActionPerformed(evt);
            }
        });
        add(AcceptBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 790, 110, 35));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 60, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Welcome to");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("EnterPrise");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void populateAlertRequestCombobox() {
        alertRequestCombo.removeAllItems();
        alertRequestCombo.addItem("Sent to Ambulance Assistant");
        alertRequestCombo.addItem("Sent to Nurse");
        alertRequestCombo.addItem("Sent to Ambulance Receptionist");
        alertRequestCombo.addItem("Accepted by Ambulance Assistants");

    }

    public void populateCriticalAlertRequest() {
        crtiticalAlertCombox.removeAllItems();
        crtiticalAlertCombox.addItem("Sent to Ambulance Assistant");
        crtiticalAlertCombox.addItem("Sent to Ambulance Receptionist");
        crtiticalAlertCombox.addItem("Accepted by Ambulance Assistants");
    }

    public void populateCriticalAlertRequestTable(String requestStatus) {
        DefaultTableModel model = (DefaultTableModel) criticalAlertRequestTable.getModel();

        model.setRowCount(0);

        for (Organization organizationTemp : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organizationTemp instanceof AmbulanceAssistantOrganization) {
                ambulanceAssistantOrganization = (AmbulanceAssistantOrganization) organizationTemp;
                System.out.println("--- in side the generateVisitPaymentRequest222222 ------------ ");
                break;
            }
        }

        WorkQueue workQueue = organization.getWorkQueue();
        System.out.println("workQueue.getWorkRequestList() size-->" + workQueue.getWorkRequestList().size());
        for (WorkRequest request : workQueue.getWorkRequestList()) {
            if (request instanceof VitalAlertRequestToAmbulanceReception) {
                VitalAlertRequestToAmbulanceReception vARTAbmuRecep = (VitalAlertRequestToAmbulanceReception) request;
                System.out.println("workQueue.getWorkRequestList() size--1111-->" + workQueue.getWorkRequestList().size());
                if (requestStatus.equals(vARTAbmuRecep.getStatus())) {
                    System.out.println("workQueue.getWorkRequestList() size--222-->" + workQueue.getWorkRequestList().size());
                    Object[] row = new Object[13];
                    row[0] = vARTAbmuRecep;
                    Date date = vARTAbmuRecep.getRequestDate();
                    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MM/dd/YYYY HH:mm:ss");
                    String dateinStr = simpleDateFormat.format(date);
                    row[1] = dateinStr;
                    row[2] = vARTAbmuRecep.getMessage();

                    Person patienttemp = vARTAbmuRecep.getSender();
                    Patient patient = (Patient) patienttemp;
                    row[3] = patient.getMrn();
                    row[4] = vARTAbmuRecep.getStatus();
                    if (vARTAbmuRecep.getReceiver() != null) {
                        row[5] = vARTAbmuRecep.getReceiver().getEmployee().getFirstName() + " " + vARTAbmuRecep.getReceiver().getEmployee().getLastName();
                        row[6] = simpleDateFormat.format(vARTAbmuRecep.getResolveDate());
                    }

                    row[7] = vARTAbmuRecep.getSecondReceiver();

                    if (vARTAbmuRecep.getSecondReceiverDate() != null) {
                        Date dateSecond = vARTAbmuRecep.getSecondReceiverDate();
                        SimpleDateFormat simpleDateFormatSeconnd = new SimpleDateFormat("MM/dd/YYYY HH:mm:ss");
                        row[8] = simpleDateFormatSeconnd.format(dateSecond);
                    }

                    model.addRow(row);
                }

            }
        }
    }


    private void AcceptBtnSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBtnSecondActionPerformed

        int selectedRow = criticalAlertRequestTable.getSelectedRow();
        if (selectedRow >= 0) {
            VitalAlertRequestToAmbulanceReception vATRTN = (VitalAlertRequestToAmbulanceReception) criticalAlertRequestTable.getValueAt(selectedRow, 0);

            System.out.println("--- in side the generateVisitPaymentRequest3333 ------------ ");
            Date date = new Date();
            vATRTN.setSecondReceiverDate(date);
            vATRTN.setSecondReceiver(userAccount);
            vATRTN.setStatus("Accepted by Ambulance Assistants");
            JOptionPane.showMessageDialog(null, "Request accepted by Ambulance Assistants");

            //Code to generate the Map
            String ambutalLati = String.valueOf(enterprise.getLatitude());
            String ambuLong = String.valueOf(enterprise.getLongitude());
            
            VitalSign vitalSign=vATRTN.getVitalSign();
            String patientlangitude=String.valueOf(vitalSign.getLatitude());
            String patientlongitude=String.valueOf(vitalSign.getLongitude());

            Browser browser = new Browser();
            BrowserView view = new BrowserView(browser);

            JFrame frame = new JFrame("Location Finder");
            //frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            frame.add(view, BorderLayout.CENTER);
            frame.setSize(900, 500);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);

            String finalURLStr = "https://www.google.com/maps/dir/'" + ambutalLati + "," + ambuLong + "'/'" + patientlangitude + "," + patientlongitude + "'";
            //String basicURL ="https://www.google.com/maps/dir/'42.3398067,-71.0891717'/'42.3471426,-71.0825182'";
            System.out.println("finalURLStr -->" + finalURLStr);
            browser.loadURL(finalURLStr);
            clearTextCritical();

        } else {
            JOptionPane.showMessageDialog(null, "Please select the request first");
        }

    }//GEN-LAST:event_AcceptBtnSecondActionPerformed

    private void viewBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtn1ActionPerformed

        int selectedRow = alertRequestTable.getSelectedRow();
        if (selectedRow >= 0) {
            VitalAlertTestRequestToNurse vATRTN = (VitalAlertTestRequestToNurse) alertRequestTable.getValueAt(selectedRow, 0);
            respRateTxt1.setText(String.valueOf(vATRTN.getVitalSign().getRespiratoryRate()));
            heartRateTxt1.setText(String.valueOf(vATRTN.getVitalSign().getHeartRate()));
            sysBloodPresTxt1.setText(String.valueOf(vATRTN.getVitalSign().getBloodPressure()));
            weightInPoundsTxt1.setText(String.valueOf(vATRTN.getVitalSign().getWeight()));

        } else {
            JOptionPane.showMessageDialog(null, "Please select the request first");
        }
    }//GEN-LAST:event_viewBtn1ActionPerformed

    private void respRateTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respRateTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respRateTxt1ActionPerformed

    private void alertRequestComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertRequestComboActionPerformed
        String requestStatus = (String) alertRequestCombo.getSelectedItem();
        System.out.println("requestStatus-->" + requestStatus);
        // below if condition to save from null value
        if (requestStatus != null) {

            if (requestStatus.equalsIgnoreCase("Sent to Ambulance Assistant")) {
                AcceptBtn.setVisible(true);
            } else {
                AcceptBtn.setVisible(false);
            }
            populateAlertRequestTable(requestStatus);
        }

    }//GEN-LAST:event_alertRequestComboActionPerformed

    private void respRateTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respRateTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respRateTxt2ActionPerformed

    private void viewBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtn2ActionPerformed

        int selectedRow = criticalAlertRequestTable.getSelectedRow();
        if (selectedRow >= 0) {
            VitalAlertRequestToAmbulanceReception vATRTN = (VitalAlertRequestToAmbulanceReception) criticalAlertRequestTable.getValueAt(selectedRow, 0);
            respRateTxt2.setText(String.valueOf(vATRTN.getVitalSign().getRespiratoryRate()));
            heartRateTxt2.setText(String.valueOf(vATRTN.getVitalSign().getHeartRate()));
            sysBloodPresTxt2.setText(String.valueOf(vATRTN.getVitalSign().getBloodPressure()));
            weightInPoundsTxt2.setText(String.valueOf(vATRTN.getVitalSign().getWeight()));

        } else {
            JOptionPane.showMessageDialog(null, "Please select the request first");
        }
    }//GEN-LAST:event_viewBtn2ActionPerformed

    private void crtiticalAlertComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crtiticalAlertComboxActionPerformed

        String requestStatus = (String) crtiticalAlertCombox.getSelectedItem();
        System.out.println("requestStatus-->" + requestStatus);
        // below if condition to save from null value
        if (requestStatus != null) {
            if (requestStatus.equalsIgnoreCase("Sent to Ambulance Assistant")) {
                AcceptBtnSecond.setVisible(true);
            } else {
                AcceptBtnSecond.setVisible(false);
            }
            populateCriticalAlertRequestTable(requestStatus);
            clearTextCritical();
        }
    }//GEN-LAST:event_crtiticalAlertComboxActionPerformed

    private void AcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBtnActionPerformed
       
        
        int selectedRow = alertRequestTable.getSelectedRow();
        if (selectedRow >= 0) {
            VitalAlertTestRequestToNurse vATRTN = (VitalAlertTestRequestToNurse) alertRequestTable.getValueAt(selectedRow, 0);

            System.out.println("--- in side the generateVisitPaymentRequest3333 ------------ ");
            Date date = new Date();
            vATRTN.setThirdReceiverDate(date);
            vATRTN.setThirdReceiver(userAccount);
            vATRTN.setStatus("Accepted by Ambulance Assistants");
            JOptionPane.showMessageDialog(null, "Request accepted by Ambulance Assistants");

            //Code to generate the Map
            String ambutalLati = String.valueOf(enterprise.getLatitude());
            String ambuLong = String.valueOf(enterprise.getLongitude());
            
            VitalSign vitalSign=vATRTN.getVitalSign();
            String patientlangitude=String.valueOf(vitalSign.getLatitude());
            String patientlongitude=String.valueOf(vitalSign.getLongitude());

            Browser browser = new Browser();
            BrowserView view = new BrowserView(browser);

            JFrame frame = new JFrame("Location Finder");
            //frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            frame.add(view, BorderLayout.CENTER);
            frame.setSize(900, 500);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);

            String finalURLStr = "https://www.google.com/maps/dir/'" + ambutalLati + "," + ambuLong + "'/'" + patientlangitude + "," + patientlongitude + "'";
            //String basicURL ="https://www.google.com/maps/dir/'42.3398067,-71.0891717'/'42.3471426,-71.0825182'";
            System.out.println("finalURLStr -->" + finalURLStr);
            browser.loadURL(finalURLStr);
            clearTextNormalRequest();
        } else {
            JOptionPane.showMessageDialog(null, "Please select the request first");
        }
        
        
    }//GEN-LAST:event_AcceptBtnActionPerformed

    public void clearTextCritical() {
        respRateTxt2.setText("");
        heartRateTxt2.setText("");
        sysBloodPresTxt2.setText("");
        weightInPoundsTxt2.setText("");
    }
    
    public void clearTextNormalRequest() {
        respRateTxt1.setText("");
        heartRateTxt1.setText("");
        sysBloodPresTxt1.setText("");
        weightInPoundsTxt1.setText("");
    }

    public void populateAlertRequestTable(String requestStatus) {
        DefaultTableModel model = (DefaultTableModel) alertRequestTable.getModel();

        for (Organization organizationTemp : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organizationTemp instanceof AmbulanceAssistantOrganization) {
                ambulanceAssistantOrganization = (AmbulanceAssistantOrganization) organizationTemp;
                System.out.println("--- in side the generateVisitPaymentRequest222222 ------------ ");
                break;

            }
        }

        model.setRowCount(0);
        WorkQueue workQueue = ambulanceAssistantOrganization.getWorkQueue();
        for (WorkRequest request : workQueue.getWorkRequestList()) {
            if (request instanceof VitalAlertTestRequestToNurse) {
                VitalAlertTestRequestToNurse vATRTNurse = (VitalAlertTestRequestToNurse) request;

                if (requestStatus.equals(vATRTNurse.getStatus())) {
                    Object[] row = new Object[13];
                    row[0] = vATRTNurse;
                    Date date = vATRTNurse.getRequestDate();
                    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MM/dd/YYYY HH:mm:ss");
                    String dateinStr = simpleDateFormat.format(date);
                    row[1] = dateinStr;
                    row[2] = vATRTNurse.getMessage();

                    Person patienttemp = vATRTNurse.getSender();
                    Patient patient = (Patient) patienttemp;
                    row[3] = patient.getMrn();
                    row[4] = vATRTNurse.getStatus();
                    if (vATRTNurse.getReceiver() != null) {
                        row[5] = vATRTNurse.getReceiver().getEmployee().getFirstName() + " " + vATRTNurse.getReceiver().getEmployee().getLastName();
                        row[6] = simpleDateFormat.format(vATRTNurse.getResolveDate());
                    }

                    row[7] = vATRTNurse.getSecondReceiver();
                    if (vATRTNurse.getSecondReceiverDate() != null) {
                        Date dateSecond = vATRTNurse.getSecondReceiverDate();
                        SimpleDateFormat simpleDateFormatSeconnd = new SimpleDateFormat("MM/dd/YYYY HH:mm:ss");
                        row[8] = simpleDateFormatSeconnd.format(dateSecond);
                    }

                    row[9] = vATRTNurse.getThirdReceiver();
                    if (vATRTNurse.getThirdReceiverDate() != null) {
                        Date dateThird = vATRTNurse.getSecondReceiverDate();
                        SimpleDateFormat simpleDateFormatThird = new SimpleDateFormat("MM/dd/YYYY HH:mm:ss");
                        row[10] = simpleDateFormatThird.format(dateThird);
                    }
                    model.addRow(row);
                }

            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptBtn;
    private javax.swing.JButton AcceptBtnSecond;
    private javax.swing.JComboBox alertRequestCombo;
    private javax.swing.JTable alertRequestTable;
    private javax.swing.JTable criticalAlertRequestTable;
    private javax.swing.JComboBox crtiticalAlertCombox;
    private javax.swing.JTextField heartRateTxt1;
    private javax.swing.JTextField heartRateTxt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField respRateTxt1;
    private javax.swing.JTextField respRateTxt2;
    private javax.swing.JTextField sysBloodPresTxt1;
    private javax.swing.JTextField sysBloodPresTxt2;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton viewBtn1;
    private javax.swing.JButton viewBtn2;
    private javax.swing.JTextField weightInPoundsTxt1;
    private javax.swing.JTextField weightInPoundsTxt2;
    // End of variables declaration//GEN-END:variables
}
