/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.EcoSystem;
import Business.EnterPrise.Enterprise;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import UserInterface.Doctor.DocShareWorkRequestReviewJPanel;
import com.ui.ChatFrame;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author samar
 */
public class PatientMainWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientMainWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization org;
    
    public PatientMainWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,Organization org, Enterprise ep, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = system;
        userAccount=account;
        enterprise=ep;
        this.org=org;
        valueLabel.setText(enterprise.getOrgName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("View Appointment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 159, 205, 35));

        jButton2.setText("View Vital Sign");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 401, 205, 35));

        jButton3.setText("View Visit Distory");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 273, 205, 35));

        jButton4.setText("Add and View Room vital Sign");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 518, -1, 35));

        jButton5.setText("View work Request");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 642, 205, 35));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 13, 60, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Welcome to");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 13, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("EnterPrise");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 13, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        System.out.println(" user account value--->" +userAccount.getPatient().getPatinetID());
        PatientViewAndTakeAppointment patientViewAndTakeAppointment = new PatientViewAndTakeAppointment(userProcessContainer,userAccount,enterprise, ecoSystem);
	userProcessContainer.add("PatientViewAndTakeAppointment", patientViewAndTakeAppointment);
	CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
	cardLayout.next(userProcessContainer);
                                           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      PatientViewAllVisitsJPanel panel = new PatientViewAllVisitsJPanel(userProcessContainer,userAccount,org, enterprise, ecoSystem);
      userProcessContainer.add("PatientViewAllVisitsJPanel", panel);
      CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
      cardLayout.next(userProcessContainer);
                                           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      PatientViewAndAddVitalSignJPanel panel = new PatientViewAndAddVitalSignJPanel(userProcessContainer,userAccount,org, enterprise, ecoSystem);
      userProcessContainer.add("PatientViewAndAddVitalSignJPanel", panel);
      CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
      cardLayout.next(userProcessContainer);
                                           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
      PatientRoomVitalSignJPanel panel = new PatientRoomVitalSignJPanel(userProcessContainer,userAccount,org, enterprise, ecoSystem);
      userProcessContainer.add("PatientRoomVitalSignJPanel", panel);
      CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
      cardLayout.next(userProcessContainer);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
      PatientViewWorkJPanel panel = new PatientViewWorkJPanel(userProcessContainer,userAccount,org, enterprise, ecoSystem);
      userProcessContainer.add("PatientViewWorkJPanel", panel);
      CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
      cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
