/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.EcoSystem;
import Business.EnterPrise.Enterprise;
import Business.EnterPrise.HospitalEnterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Samarth
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    private UserAccount userAccount;
    private Organization organization;
    public AdminWorkAreaJPanel(JPanel userProcessContainer,UserAccount account, Organization organization, Enterprise enterprise,EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        ecoSystem=system;
        valueLabel.setText(enterprise.getOrgName());
        this.userAccount=account;
        this.organization=organization;
        //System.out.println("Enterprise name--->"+enterprise.getOrgName());
        showHideandShowButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        viewWorkReBtn = new javax.swing.JButton();
        createFieldCriveBtn = new javax.swing.JButton();
        viewAnalyReportbtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Aminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        userJButton.setText("Manage User");
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 150, 35));

        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 150, 35));

        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, 35));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 60, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Welcome to");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("EnterPrise");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, -1));

        viewWorkReBtn.setText("View Work Request");
        viewWorkReBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewWorkReBtnActionPerformed(evt);
            }
        });
        add(viewWorkReBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 150, 35));

        createFieldCriveBtn.setText("Create Field Drives");
        createFieldCriveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFieldCriveBtnActionPerformed(evt);
            }
        });
        add(createFieldCriveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 150, 35));

        viewAnalyReportbtn.setText("View Analytics Report");
        viewAnalyReportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAnalyReportbtnActionPerformed(evt);
            }
        });
        add(viewAnalyReportbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, -1, 35));
    }// </editor-fold>//GEN-END:initComponents

    
    public void showHideandShowButton()
    {
      if(enterprise instanceof HospitalEnterprise)
      {
          viewWorkReBtn.setVisible(true);
          createFieldCriveBtn.setVisible(true);
          viewAnalyReportbtn.setVisible(true);
      }
      else
      {
          viewWorkReBtn.setVisible(false);
          createFieldCriveBtn.setVisible(false);
          viewAnalyReportbtn.setVisible(false);
      }
    }
    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise,ecoSystem);
        userProcessContainer.add("ManageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise,ecoSystem);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void viewWorkReBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewWorkReBtnActionPerformed
      EnterPriseWorkRequestJPanel enterPriseWorkRequestJPanel = new EnterPriseWorkRequestJPanel(userProcessContainer,userAccount,organization, enterprise,ecoSystem);
        userProcessContainer.add("EnterPriseWorkRequestJPanel", enterPriseWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewWorkReBtnActionPerformed

    private void createFieldCriveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFieldCriveBtnActionPerformed
        CreateFieldDriveForPatients createFieldDriveForPatients = new CreateFieldDriveForPatients(userProcessContainer,userAccount,organization, enterprise,ecoSystem);
        userProcessContainer.add("CreateFieldDriveForPatients", createFieldDriveForPatients);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createFieldCriveBtnActionPerformed

    private void viewAnalyReportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAnalyReportbtnActionPerformed
       ViewAnalysisReportJPanel viewAnalysisReportJPanel = new ViewAnalysisReportJPanel(userProcessContainer,userAccount,organization, enterprise,ecoSystem);
        userProcessContainer.add("viewAnalysisReportJPanel", viewAnalysisReportJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewAnalyReportbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createFieldCriveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton userJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton viewAnalyReportbtn;
    private javax.swing.JButton viewWorkReBtn;
    // End of variables declaration//GEN-END:variables
}
