/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Pharmacist;

import Business.EcoSystem;
import Business.EnterPrise.Enterprise;
import Business.Organization.NurseOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacistOrganization;
import Business.PatientVisit.Medication;
import Business.PatientVisit.Prescription;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MedicineWorkRequest;
import Business.WorkQueue.VitalTestWorkRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samar
 */
public class PharmacistWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacistWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    private PharmacistOrganization pharmacistOrganization;
    public PharmacistWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,Organization organization,Enterprise enterprise,EcoSystem business) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        userAccount=account;
        if(organization instanceof PharmacistOrganization)
        {
           pharmacistOrganization=(PharmacistOrganization)organization; 
        }
        
        this.enterprise=enterprise;
        this.ecoSystem=ecoSystem;
        populateStatusCombobox();
        populateTable("Sent");
        valueLabel.setText(enterprise.getOrgName());
    }

     public void populateStatusCombobox()
    {
      System.out.println(" ------ inside populateStatusCombobox--------");
      requestStatusComboBox.removeAllItems();
      requestStatusComboBox.addItem("Sent");
      requestStatusComboBox.addItem("Completed");
    }
    
     public void populateTable(String requestStatus)
    {
        System.out.println(" ------ inside populateTable--------");
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        WorkQueue workQueue=pharmacistOrganization.getWorkQueue();
        System.out.println("in side the populate Table+--requestStatus--->"+requestStatus);
        for(WorkRequest request : workQueue.getWorkRequestList())
        {
            if(request instanceof MedicineWorkRequest)
           {
            MedicineWorkRequest meWorkReq=(MedicineWorkRequest)request;
            
            if(requestStatus.equals(meWorkReq.getStatus()))
            {
            Object[] row = new Object[8];
            row[0] = meWorkReq;
            Date date=meWorkReq.getRequestDate();
            SimpleDateFormat simpleDateFormat=new SimpleDateFormat("MM/dd/YYYY");
            String dateinStr=simpleDateFormat.format(date);
            row[1] = dateinStr;
            row[2] = meWorkReq.getStatus();
            row[3] = meWorkReq.getVisit().getPatient().getFirstName()+" "+meWorkReq.getVisit().getPatient().getFirstName();
            row[4] = meWorkReq.getVisit().getPatient().getMrn();
            if(meWorkReq.getReceiver()!=null)
            {
             row[5] = meWorkReq.getReceiver().getEmployee().getFirstName()+" " +meWorkReq.getReceiver().getEmployee().getLastName();   
            }
            if(meWorkReq.getResolveDate()!=null)
            {
            Date resDate=meWorkReq.getResolveDate();
            SimpleDateFormat simpleDateFormat1= new SimpleDateFormat("MM/dd/YYYY");
            
            row[6] = simpleDateFormat1.format(resDate);   
            }
            
                      
            model.addRow(row); 
            }
            
        }
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requestStatusComboBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        medicationTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pharmacist Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 35, -1, -1));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Doctor Name", "Requested Date", "Status", "Patient Name", "patient MRN", "Receiver Name", "Received Date"
            }
        ));
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 155, 790, 96));

        requestStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        requestStatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestStatusComboBoxActionPerformed(evt);
            }
        });
        add(requestStatusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 102, 35));

        medicationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Medicine Name", "Dose", "Start Date", "End Date", "No of Days", "Total No of medicine"
            }
        ));
        jScrollPane2.setViewportView(medicationTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 790, 90));

        jButton1.setText("View Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 140, 35));

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 510, 100, 35));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 60, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Welcome to");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("EnterPrise");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        DefaultTableModel model = (DefaultTableModel)medicationTable.getModel();
        
        model.setRowCount(0);
        
       int selectedRow=workRequestJTable.getSelectedRow();
       if(selectedRow>=0)
        {
            MedicineWorkRequest medicineWorkRequest =(MedicineWorkRequest)workRequestJTable.getValueAt(selectedRow,0);
            Prescription prescription= medicineWorkRequest.getVisit().getPrescription();
            for(Medication medication:prescription.getMedicationList().getMedicationList())
            {
               Object[] row = new Object[8];
               row[0] = medication;
               row[1] = medication.getDose();
               row[2] = medication.getStartDate();
               row[3] = medication.getEndDate();
               row[4] = medication.getForNoOfDays();
               row[5] = medication.getTotalNumberOfMedicine();
               model.addRow(row); 
            }
        }
       else
       {
           JOptionPane.showMessageDialog(null, "Please select the request first");
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
       
       int selectedRow=workRequestJTable.getSelectedRow();
       if(selectedRow>=0)
        {
            MedicineWorkRequest medicineWorkRequest =(MedicineWorkRequest)workRequestJTable.getValueAt(selectedRow,0);
            
            Date todayDate=new Date();
            medicineWorkRequest.setResolveDate(todayDate);
            medicineWorkRequest.setReceiver(userAccount);
            medicineWorkRequest.setStatus("Completed");
            DefaultTableModel model = (DefaultTableModel)medicationTable.getModel();
            model.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Thanks for Process");
            populateTable("Sent");
        }
       else
       {
        JOptionPane.showMessageDialog(null, "Please select the request first");   
       }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void requestStatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestStatusComboBoxActionPerformed
        String strReqStatus = (String) requestStatusComboBox.getSelectedItem();
        System.out.println("----- in side the combos selecr--------");
        if (strReqStatus != null){
            
            if(strReqStatus.equalsIgnoreCase("Completed"))
            {
                submitBtn.setVisible(false);
            }
            else
            {
                submitBtn.setVisible(true); 
            }
            populateTable(strReqStatus);
        }
        
        
    }//GEN-LAST:event_requestStatusComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable medicationTable;
    private javax.swing.JComboBox requestStatusComboBox;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
