/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FieldDriveForPatient;

import Business.EcoSystem;
import Business.EnterPrise.Enterprise;
import Business.FieldDrive.FieldDriveForPatients;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FieldDrivePatientWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.Patient.PatientViewAndAddVitalSignJPanel;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samar
 */
public class FieldDriveWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form FieldDriveWorkArea
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    
    public FieldDriveWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=account;
        this.organization=organization;
        this.enterprise=enterprise;
        ecoSystem=business;
        populateUserworkRequest();
         System.out.println("userAccount===>"+userAccount.getUsername());
        System.out.println("=====in side constructor-====="); 
        System.out.println("userAccount===>"+userAccount.getWorkQueue().getWorkRequestList().size());
        System.out.println("userAccount===>"+userAccount);
   }
    public void populateUserworkRequest()
    {
      DefaultTableModel model = (DefaultTableModel) userWorkRequestTable.getModel();
        model.setRowCount(0);
        
        
        System.out.println("userAccount.getWorkQueue().getWorkRequestList()-->"+userAccount.getWorkQueue().getWorkRequestList());
        for (WorkRequest workRequest : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[3];
            SimpleDateFormat sdf1 = new SimpleDateFormat("MM/dd/YYYY");
            //String lastDate = sdf1.format(date1);
            if( workRequest instanceof FieldDrivePatientWorkRequest)
            {
               FieldDrivePatientWorkRequest fDPWR=(FieldDrivePatientWorkRequest)workRequest;
               row[0]=fDPWR;
               row[1]=sdf1.format(fDPWR.getStartDate());
               row[2]=sdf1.format(fDPWR.getEndDate());
            }
            model.addRow(row);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userWorkRequestTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Field Drive for Patient Registration");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 34, -1, -1));

        userWorkRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drive Name", "Start Date", "End Date"
            }
        ));
        jScrollPane1.setViewportView(userWorkRequestTable);
        if (userWorkRequestTable.getColumnModel().getColumnCount() > 0) {
            userWorkRequestTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 119, 912, 95));

        jButton1.setText("Create Person Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 180, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        FieldDriveCreatePersonProfileJPanel fieldDriveCreatePersonProfileJPanel = new FieldDriveCreatePersonProfileJPanel(userProcessContainer,enterprise ,ecoSystem);
        userProcessContainer.add("fieldDriveCreatePersonProfileJPanel", fieldDriveCreatePersonProfileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable userWorkRequestTable;
    // End of variables declaration//GEN-END:variables
}
